name: check-header

on:
  pull_request

concurrency:
      group: ${{ github.ref }}-${{ github.workflow }}
      cancel-in-progress: true

jobs:
  check-headers:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v4
      with:
        # required to grab the history of the PR
        fetch-depth: 0

    - name: Get changed files
      run: |
        echo "files=$(git diff --name-only ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} | tr '\n' ',')" >> $GITHUB_ENV

    - uses: ./.github/actions/verify-headers
      with:
        files: "${{ env.files }}"
